# Generated by Django 6.0.1 on 2026-01-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='freeze_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
