# Generated by Django 6.0.1 on 2026-01-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account_status_user_freeze_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold'), ('vip', 'VIP')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='freeze_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
